# project:
#   name: "BDA"
#   version: "1.0.0"

# paths:
#   base_dir: null  # Will be set programmatically
#   faiss_index_dir: "vector_stores/faiss_index"
#   vector_store_dir: "vector_stores"

llm:
  provider: "openai"
  model_name: "o3-mini"
#   temperature: 0.0
  max_tokens: null
  streaming: true
  additional_params: {}

embedding:
  provider: "huggingface"
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  additional_params: {}

vector_store:
  provider: "pgvector"
  collection_name: "chunk_embeddings"

  additional_params: {}

# chunking:
#   chunk_size: 512
#   chunk_overlap: 200

retrieval:
  method: "default"
  k: 5

#   params: 
#     score_threshold: 0.5
#     prioritize_semantic: true
#     weights: [0.7, 0.3]
#     reranker_model: colbert
#     reranker_threshold: 0.7

storage:
  provider: supabase

database:
  provider: postgres
  additional_params: {} 